blank_issues_enabled: false
contact_links:
  - name: Ask a question or start a discussion
    url: https://github.com/liquidctl/liquidctl/discussions
    about: "Ask the maintainers and the community questions or start a discussion."
