name: New device request
description: Request support for new devices.
labels: ["new device"]
body:
  - type: input
    id: device-type
    attributes:
      label: Device type
      description: What kind of device are you requesting support for?
      placeholder: e.g. AIO liquid cooler
    validations:
      required: true
  - type: input
    id: product-page
    attributes:
      label: Product page
      description: Please provide a link to the manufacturer's product page for your exact device.
      placeholder:  e.g. https://www.corsair.com/[...]
    validations:
      required: true
  - type: input
    id: first-party-software
    attributes:
      label: First-party software
      description: What software is provided by the manufacture to control the device?
      placeholder: e.g. Corsair iCue
    validations:
      required: true
  - type: dropdown
    id: features-monitoring
    attributes:
      label: What monitoring functionality does the device support?
      description: Select as many options as apply, not mandatory.
      multiple: true
      options:
        - temperatures
        - fan/pump speeds or duty cycles
        - voltages, currents or power measurements
    validations:
      required: false
  - type: dropdown
    id: features-configuration
    attributes:
      label: What configuration functionality does the device support?
      description: Select as many options as apply, not mandatory.
      multiple: true
      options:
        - fan/pump speeds or duty cycles
        - voltages, current or power limits
        - lighting of embedded LEDs
        - lighting of accessories like RGB fans or LED strips
    validations:
      required: false
  - type: input
    id: physical-connection
    attributes:
      label: Physical connection
      description: The device is physically connected to the host system using which connector?
      placeholder: e.g. USB header, PCI-e slot, onboard, other
    validations:
      required: false
  - type: input
    id: connection-protocol
    attributes:
      label: Connection protocol
      description: The device uses which protocol to communicate with the host system?
      placeholder: e.g. HID, USB, I²C, SMBus, other
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information about the device
      description: Include any useful additional information, such as USB vendor and product IDs, the output of `lsusb -v` (Linux) or `system_profiler SPUSBDataType` (Mac OS), links to external resources or already collected traffic data.
      placeholder: |
        <!-- An example code block: -->
        ```
        $ libusb -v
        Bus 001 Device 007 ID 1e71:1714 NZXT Smart Device
        Device Descriptor [ ... ]
        ```
    validations:
      required: false
  - type: dropdown
    id: can-help-with
    attributes:
      label: Can you help with implementing or testing the changes needed for liquidctl to support this device?
      description: Select as many options as apply, not mandatory.
      multiple: true
      options:
        - testing changes on Linux
        - testing changes on Windows
        - testing changes on Mac OS
        - attempting to capture USB/HID traffic
        - attempting to capture I²C/SMBus traffic
        - analyzing traffic data
        - documenting the protocol
        - implementing the changes
    validations:
      required: false
